driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
provisioner: chef_zero

platforms:
  - name: ubuntu-13.04
    driver_config:
        box: opscode-ubuntu-13.04
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
  - name: ubuntu-12.10
    driver_config:
        box: opscode-ubuntu-12.10
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.10_provisionerless.box
  - name: ubuntu-12.04
    driver_config:
        box: opscode-ubuntu-12.04
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  - name: ubuntu-10.04
    driver_config:
        box: opscode-ubuntu-10.04
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  - name: debian-7.0.0
    driver_config:
        box: opscode-debian-7.0.0
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.0.0_provisionerless.box
  - name: debian-7.1.0
    driver_config:
        box: opscode-debian-7.1.0
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box
  - name: centos-6.4
    driver_config:
        box: opscode-centos-6.4
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
  - name: centos-5.9
    driver_config:
        box: opscode-centos-5.9
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
  - name: fedora-18
    driver_config:
        box: opscode-fedora-18
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_fedora-18_provisionerless.box
  - name: fedora-19
    driver_config:
        box: opscode-fedora-19
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_fedora-19_provisionerless.box
  - name: fedora-20
    driver_config:
        box: opscode-fedora-20
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_fedora-20-x86_64_provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[sk_ruby]
