driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 4

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: ubuntu-13.04
    driver_config:
        box: opscode-ubuntu-13.04
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
  - name: ubuntu-10.04
    driver_config:
        box: opscode-ubuntu-10.04
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  - name: centos-6.4
    driver_config:
        box: opscode-centos-6.4
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
  - name: centos-5.9
    driver_config:
        box: opscode-centos-5.9
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
#  - name: fedora-20
#    driver_config:
#        box: opscode-fedora-20
#        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_fedora-20-x86_64_provisionerless.box
#  - name: freebsd-9.2
#    driver_config:
#        box: freebsd-9.2
#        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_freebsd-9.2_chef-provisionerless.box

suites:
  - name: default
    run_list: fake::default
  - name: single
    run_list: fake::single
