driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 4

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-10.04
  - name: centos-6.5
  - name: centos-5.10
#  - name: debian-6.0.8
#  - name: debian-7.4
#  - name: fedora-20
#  - name: freebsd-9.2
#  - name: freebsd-10

suites:
  - name: default
    run_list: fake::default
  - name: single
    run_list: fake::single
