# People who care about this need to get a life
StringLiterals:
  Enabled: false
# People who care about this need to learn to open up wider windows
LineLength:
  Enabled: false
# Method names should be as long as they need to be
MethodLength:
  Enabled: false
# Chef supports/requires ruby 1.8 hash syntax
HashSyntax:
  Enabled: false
# I use spaces inside parens/brackets when I feel it increases readability
SpaceInsideParens:
  Enabled: false
SpaceInsideBrackets:
  Enabled: false
# Nope, not doing this
SignalException:
  Enabled: false
