ClassLength:
  Enabled: false
CommentAnnotation:
  Enabled: false
Documentation:
  Enabled: false
DoubleNegation:
  Enabled: false
Encoding:
  Enabled: false
FormatString:
  Enabled: false
IfUnlessModifier:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
PercentLiteralDelimiters:
  Enabled: false
SignalException:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
SpaceInsideBrackets:
  Enabled: false
SpaceInsideParens:
  Enabled: false
StringLiterals:
  Enabled: false
TrailingComma:
  EnforcedStyleForMultiline: comma
