# Everyone who cares about StringLiterals needs to die in an AIDS fire, Fuck all those pedants
StringLiterals:
  Enabled: false
# 80 character terminal widths were not handed down by God.  Fuck the hell off.
LineLength:
  Enabled: false
# Chef supports ruby 1.8 hash syntax
HashSyntax:
  Enabled: false
# I use spaces inside parens/brackets when I feel it increases readability
SpaceInsideParens:
  Enabled: false
SpaceInsideBrackets:
  Enabled: false

