ClassLength:
  Enabled: false
CommentAnnotation:
  Enabled: false
Encoding:
  Enabled: false
FavorSprintf:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SignalException:
  Enabled: false
SpaceInsideBrackets:
  Enabled: false
SpaceInsideParens:
  Enabled: false
StringLiterals:
  Enabled: false
TrailingComma:
  EnforcedStyleForMultiline: comma
