rvm:
  - 1.9.3
  - 2.0.0
before_script:
  - bundle exec berks install
script:
  - bundle exec foodcritic -t '~FC023' -t '~FC019' -t '~FC048' -f any .
#  - bundle exec rspec --color --format progress
  - bundle exec rubocop
